### ISSUE TITLE
Need More Documentation

### ISSUE THREAD

**Issue by cadencetech** [crabshank/Draw-3D-straight-lines-on-2D-images#1]
This works with mp4 video files only?  Is there a detailed explanation on exactly what the drawn box can be used for and the shaded beam.  I would like to use for selecting regions of interest and regions to be ignored.  Is that possible?

**Comment by crabshank** [comment]
It works with any media that HTML5 supports. The box is just for calibration, i.e. two/four lines (bounded by cyan circle) drawn over lines that are parallel within the image (as shown in the YouTube video).
